### ISSUE TITLE
extra directory packed

### ISSUE THREAD

**Issue by chorny** [jonasbn/Date-Holidays#10]
local
See https://metacpan.org/source/JONASBN/Date-Holidays-1.04/local

**Comment by jonasbn** [comment]
Darn, I will fix it ASAP - thanks

**Comment by jonasbn** [comment]
Hi Alexandr, 

Release 1.05 has gone out, thanks for the bug report. 

jonasbn

**Comment by jonasbn** [comment]
Hi @chorny 

I have been thinking a bit about this issue and monitoring the file size could have caught it. Do you happen to know any Kwalitee / Dist::Zilla or other tools, which could help in avoiding this issue in the future?

jonasbn

**Comment by chorny** [comment]
AFAIK they all do not test archive that was prepared for release. But I don't use D::Z, so it would be better to ask here https://metacpan.org/pod/Dist::Zilla#SUPPORT
